In [1]:
# Dataset source - Kaggle - https://www.kaggle.com/saivamshi/cricket-world-cup-2019-players-data - 'ODI_Match_Results.csv' file.

import numpy as np
import pandas as pd
import datetime
import matplotlib.pyplot as plt

df = pd.read_csv('D:/Users/Bhuvanjeet/Desktop/cricket/ODI_Match_Results.csv') 


y = df['Result']

X = df.loc[:,['Margin','Toss','Bat','Opposition','Ground','Country']]


from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
#X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
onehotencoder = OneHotEncoder()
#X = X.replace('<', '', regex=True)
X = onehotencoder.fit_transform(X).toarray()
# Encoding the Dependent Variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


# Applying LDA
#from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
#lda = LDA(n_components = 2)
#X_train = lda.fit_transform(X_train, y_train)
#X_test = lda.transform(X_test)

# Applying PCA
#from sklearn.decomposition import PCA
#pca = PCA(n_components = 2)
#X_train = pca.fit_transform(X_train)
#X_test = pca.transform(X_test)
#explained_variance = pca.explained_variance_ratio_
#explained_variance

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
y_test
print(cm) #printing confusion matrix

[[  4   0   0   0   0]
 [  0 117   0   0  23]
 [  2   0  12   0   0]
 [  0   0   2   0   0]
 [  0  33   0   0 138]]
